### ISSUE TITLE
Typescript can not find declaration file TS7016

### ISSUE THREAD

**Issue by ngeien** [natterstefan/react-component-catalog#68]
# Bug Report

## Relevant information

Typescript can not find a declaration file for module 'react-component-catalog' TS7016.

### Your Environment

* OS: Ubuntu 20.04
* Node: v12.20.2
* Package Version: 2.1.0

### Steps to reproduce

```shell
yarn create react-app my-app --template typescript
cd my-app
yarn add react-component-catalog
yarn start
```

Add ```import { useCatalog } from 'react-component-catalog';``` to any code file.
Typescript shows an error TS7016: Could not find a declaration file for module 'react-component-catalog'.

**Comment by natterstefan** [comment]
Hi @ngeien,

thanks for the report. I'll take a look at this.

**Comment by majo44** [comment]
Seems the build is broken, and is putting the declarations in wrong place:
![image](https://user-images.githubusercontent.com/2294352/112653257-87b03f00-8e4e-11eb-8a4b-dbe1799705e7.png)
Declaration in package.json
![image](https://user-images.githubusercontent.com/2294352/112653297-90087a00-8e4e-11eb-9ab8-f5e9dac1aea2.png)

**Comment by natterstefan** [comment]
Hi @ngeien, hi @majo44,

I just published (https://github.com/natterstefan/react-component-catalog/releases/tag/v2.1.1). Let me know if this fixes your issue.

Take care.

**Comment by majo44** [comment]
Thanks a lot for quick release, 
Types now works fine.
Best regards

**Comment by ngeien** [comment]
Hi @natterstefan,
works fine.
Thank you!
